import { describe, it, expect } from 'vitest';
import { TRACK_IDS, TRACKS, courseObjects, pointAt, projectOnTrack, trackLength, angleDelta, type TrackId } from '../shared/track.ts';
import { createRace, makeRacer, neutralInput, cleanInput, stepRace, placeRacer, addStone, useItem, useAbility, hit, recover, syncInventory, RACERS, ABILITY_IDS, type Item, type Race } from '../shared/game.ts';
const tick = (r: Race, seconds: number) => { for (let i = 0; i < seconds * 60; i++) stepRace(r); };
function solo(track: TrackId = 'test') { const r = createRace(track, [makeRacer('you', 'Test')], 1, 42, 'time'); r.time = .1; r.phase = 'racing'; return r; }
function duel() { const r = createRace('test', [makeRacer('a', 'A'), makeRacer('b', 'B', 1)], 1, 42, 'versus'); r.time = .1; r.phase = 'racing'; placeRacer(r.track, r.racers[0], 0); placeRacer(r.track, r.racers[1], 14); return r; }
function speed(r: Race, index: number, v: number) { const p = r.racers[index]; p.vx = Math.sin(p.yaw) * v; p.vz = Math.cos(p.yaw) * v; p.speed = Math.abs(v); }
describe('courses and canonical roster', () => {
  it('has eight distinct courses, vehicles and independently selectable abilities', () => { expect(TRACK_IDS).toHaveLength(8); expect(new Set(RACERS.map(r => r.vehicle)).size).toBe(8); for (let i = 0; i < 8; i++) expect(makeRacer('p', 'Test', i, false, ABILITY_IDS[(i + 2) % 8]).abilityId).toBe(ABILITY_IDS[(i + 2) % 8]); });
  for (const id of TRACK_IDS) it(`${id}: continuous closed path, projection and colored pickup layout`, () => { const len = trackLength(id); expect(len).toBeGreaterThan(1200); const a = pointAt(id, 0), b = pointAt(id, len); expect(Math.hypot(a.x - b.x, a.z - b.z)).toBeLessThan(.001); for (let s = 10; s < len; s += 70) { const p = pointAt(id, s, 4), q = projectOnTrack(id, p.x, p.z, s); expect(Math.abs(q.s - s)).toBeLessThan(1); expect(q.offset).toBeCloseTo(4, 1); } const objects = courseObjects(id); expect(objects.stones).toHaveLength(36); expect(new Set(objects.stones.map(s => s.kind)).size).toBeGreaterThan(5); });
});
describe('free world-space driving', () => {
  it('does not steer automatically or follow a rail', () => { const r = solo('forest'), p = r.racers[0]; placeRacer(r.track, p, 80); p.input.throttle = true; const yaw = p.yaw, x = p.px, z = p.pz; tick(r, 1); expect(p.yaw).toBeCloseTo(yaw, 9); expect(Math.abs((p.px - x) * Math.cos(yaw) - (p.pz - z) * Math.sin(yaw))).toBeLessThan(.001); });
  it('accelerates, turns actual heading, brakes to rest and reverses', () => { const r = solo(), p = r.racers[0]; p.input.throttle = true; tick(r, 1); expect(p.speed).toBeGreaterThan(20); const yaw = p.yaw; p.input.steer = .5; tick(r, .3); expect(angleDelta(p.yaw, yaw)).toBeGreaterThan(.1); p.input = { ...neutralInput(), brake: true }; tick(r, 1); expect(p.speed).toBeLessThan(.01); p.input = { ...neutralInput(), reverse: true }; tick(r, 1); expect(p.vx * Math.sin(p.yaw) + p.vz * Math.cos(p.yaw)).toBeLessThan(-9); expect(p.wrongWay).toBe(true); });
  it('does not credit a reverse crossing or skipped checkpoint', () => { const r = solo(), p = r.racers[0], len = trackLength(r.track); placeRacer(r.track, p, len - 1); p.input.throttle = true; tick(r, .8); expect(p.gates).toBe(0); expect(p.finishTime).toBeNull(); placeRacer(r.track, p, 1); p.input = { ...neutralInput(), reverse: true }; tick(r, 1); expect(p.lapTimes).toHaveLength(0); expect(p.gates).toBe(0); });
  it('bounces off walls without resetting heading', () => { const r = solo(), p = r.racers[0]; placeRacer(r.track, p, 20, TRACKS.test.width); p.yaw += Math.PI / 2; const yaw = p.yaw; speed(r, 0, 30); p.input.throttle = true; tick(r, .3); const q = projectOnTrack(r.track, p.px, p.pz, p.routeS); expect(Math.abs(q.offset)).toBeLessThan(TRACKS.test.width + .8); expect(p.yaw).toBeCloseTo(yaw, 7); expect(r.events.some(e => e.type === 'wall')).toBe(true); });
  it('falls off cliffs then returns to the saved road position', () => { const r = solo('gardens'), p = r.racers[0]; placeRacer(r.track, p, 20, TRACKS.gardens.width + 7); p.lastSafeS = 10; stepRace(r); expect(p.falling).toBeGreaterThan(0); tick(r, 1.4); expect(p.falling).toBe(0); expect(Math.abs(p.x)).toBeLessThan(.1); expect(p.s).toBeLessThan(11); });
  it('recovery cannot skip an unvisited gate', () => { const r = solo(), p = r.racers[0]; p.lastSafeS = 9999; recover(r, p); expect(p.s).toBeLessThan(trackLength(r.track) / 12); expect(p.gates).toBe(0); expect(p.speed).toBe(0); });
  it('a held accelerator is not a dash start, but a timed press is', () => { const a = createRace('test', [makeRacer('p', 'P')], 1, 1, 'time'); a.racers[0].input.throttle = true; tick(a, 3.7); expect(a.events.some(e => e.type === 'start')).toBe(false); const b = createRace('test', [makeRacer('p', 'P')], 1, 1, 'time'); tick(b, 3.35); b.racers[0].input.throttle = true; tick(b, .3); expect(b.events.some(e => e.type === 'start')).toBe(true); });
  it('drifting has no release boost; excess drift spins and release/repress performs Spin Dash', () => { const r = solo(), p = r.racers[0]; speed(r, 0, 25); p.input = { ...neutralInput(), throttle: true, drift: true, steer: .2 }; tick(r, .5); expect(p.drift).toBeGreaterThan(.4); p.input.drift = false; p.input.steer = 0; stepRace(r); expect(p.boost).toBe(0); p.drift = 2.8; p.input.drift = true; p.input.steer = .2; stepRace(r); expect(p.stun).toBeGreaterThan(0); expect(p.spinDash).toBe(true); p.input = neutralInput(); stepRace(r); p.input.throttle = true; stepRace(r); expect(p.stun).toBe(0); expect(p.boost).toBeGreaterThan(1); expect(r.events.some(e => e.type === 'spindash')).toBe(true); });
  it('only accepts bounded inputs, never client positions or nonboolean buttons', () => { expect(cleanInput({ steer: Infinity, throttle: 1, item: 'true', px: 1e9 })).toEqual(neutralInput()); expect(cleanInput({ steer: 20, reverse: true })).toEqual({ ...neutralInput(), steer: 1, reverse: true }); });
});
describe('three trailing Magic Stones', () => {
  it('has physical capacity three and consumes last-in-first-out contiguous groups', () => { const r = solo(), p = r.racers[0]; addStone(p, 'fire'); addStone(p, 'ice'); addStone(p, 'fire'); expect(addStone(p, 'haste')).toBe(false); expect(p.itemLevel).toBe(1); useItem(r, p); expect(p.stones).toEqual(['fire', 'ice']); expect(p.item).toBe('ice'); useItem(r, p); expect(p.stones).toEqual(['fire']); addStone(p, 'fire'); addStone(p, 'fire'); expect(p.itemLevel).toBe(3); useItem(r, p); expect(p.stones).toHaveLength(0); });
  it('Reflect and Doom remain individual stones', () => { const p = makeRacer('p', 'P'); for (const kind of ['shield', 'doom'] as Item[]) { p.stones = [kind, kind, kind]; syncInventory(p); expect(p.itemLevel).toBe(1); } });
  it('Fire is an aimed projectile, Fira homes, Firaga targets every opponent', () => { const r = duel(), p = r.racers[0]; addStone(p, 'fire'); useItem(r, p); expect(r.projectiles[0].target).toBeNull(); tick(r, .2); expect(r.racers[1].stun).toBeGreaterThan(0); r.projectiles = []; addStone(p, 'fire'); addStone(p, 'fire'); useItem(r, p); expect(r.projectiles[0].target).toBe('b'); r.projectiles = []; p.stones = ['fire', 'fire', 'fire']; useItem(r, p); expect(r.projectiles).toHaveLength(r.racers.length - 1); });
  it('an aimed Fire misses a rival out of its line', () => { const r = duel(), p = r.racers[0]; placeRacer(r.track, r.racers[1], 14, 8); addStone(p, 'fire'); useItem(r, p); tick(r, .4); expect(r.racers[1].stun).toBe(0); });
  it('Blizzard drops one trap, Blizzara six, Blizzaga freezes rivals', () => { const r = duel(), p = r.racers[0]; for (let level = 1; level <= 3; level++) { r.traps = []; p.stones = new Array(level).fill('ice'); useItem(r, p); if (level < 3) expect(r.traps).toHaveLength(level === 1 ? 1 : 6); else expect(r.racers[1].stun).toBeGreaterThan(0); } });
  it('Thunder and Ultima crash, Mini shrinks and Haste boosts', () => { for (const kind of ['thunder', 'ultima', 'mini', 'haste'] as Item[]) { const r = duel(), p = r.racers[0], q = r.racers[1]; p.stones = [kind, kind, kind]; useItem(r, p); if (kind === 'mini') { expect(q.miniLevel).toBe(3); expect(q.mini).toBeGreaterThan(0); } else if (kind === 'haste') expect(p.boost).toBeGreaterThan(4); else expect(q.stun).toBeGreaterThan(1); } });
  it('held Reflect intercepts automatically and returns the attack without loops', () => { const r = duel(), [p, q] = r.racers; addStone(q, 'shield'); hit(r, q, p, 'thunder'); expect(q.stun).toBe(0); expect(q.stones).toHaveLength(0); expect(p.stun).toBeGreaterThan(0); p.invincible = p.stun = 0; addStone(p, 'shield'); addStone(q, 'shield'); hit(r, q, p, 'fire'); expect(p.stones).toHaveLength(0); expect(q.stones).toHaveLength(0); expect(p.stun).toBe(0); });
  it('manually cast Reflect returns small attacks; area and Ice spells are blocked rather than reflected', () => { const r = duel(), [p, q] = r.racers; addStone(q, 'shield'); useItem(r, q); hit(r, q, p, 'fire'); expect(q.stun).toBe(0); expect(p.stun).toBeGreaterThan(0); for (const [kind, level] of [['ultima', 1], ['ice', 1], ['fire', 3]] as [Item, number][]) { p.stun = p.invincible = 0; hit(r, q, p, kind, level); expect(q.stun).toBe(0); expect(p.stun).toBe(0); } });
  it('cloud and carpet racers ignore ground ice but not Blizzaga', () => { const r = duel(), [p, q] = r.racers; q.character = 4; hit(r, q, p, 'ice', 1); expect(q.stun).toBe(0); hit(r, q, p, 'ice', 3); expect(q.stun).toBeGreaterThan(0); });
  it('Doom transfers exactly once per bump and detonates after ten seconds', () => { const r = duel(), [p, q] = r.racers; hit(r, q, p, 'doom'); expect(q.doom).toBe(10); placeRacer(r.track, p, 13); stepRace(r); expect(p.doom).toBeGreaterThan(9); expect(q.doom).toBe(0); placeRacer(r.track, q, 30); tick(r, 10); expect(p.stun).toBeGreaterThan(3); expect(r.events.some(e => e.type === 'doom-pass')).toBe(true); });
  it('casts only on the input edge, not continuously while held', () => { const r = solo(), p = r.racers[0]; p.stones = ['fire', 'haste']; syncInventory(p); p.input.item = true; tick(r, .5); expect(p.stones).toEqual(['fire']); p.input.item = false; stepRace(r); p.input.item = true; stepRace(r); expect(p.stones).toHaveLength(0); });
  it('Time Attack is solo and has no course pickups', () => { const r = solo(), p = r.racers[0], st = courseObjects(r.track).stones[0]; placeRacer(r.track, p, st.s, st.x); tick(r, .1); expect(r.racers).toHaveLength(1); expect(p.stones).toHaveLength(0); });
  it('a real pickup occupies an inventory slot and respawns', () => { const r = duel(), p = r.racers[0], st = courseObjects(r.track).stones[0]; placeRacer(r.track, p, st.s, st.x); stepRace(r); expect(p.stones).toHaveLength(1); expect(r.pickups[st.id]).toBeGreaterThan(1); placeRacer(r.track, p, 0); tick(r, 1.2); expect(r.pickups[st.id]).toBe(0); });
});
describe('independent abilities', () => {
  for (const id of ['dash', 'flap', 'grip', 'charge'] as const) it(`${id} activates and spends a full gauge`, () => { const r = solo(), p = r.racers[0]; p.abilityId = id; p.ability = 100; useAbility(r, p); expect(p.ability).toBe(0); expect(p[id === 'flap' ? 'flying' : id === 'grip' ? 'gripUp' : 'boost']).toBeGreaterThan(0); });
  it('Mug steals the latest stone but cannot exceed capacity', () => { const r = duel(), [p, q] = r.racers; p.abilityId = 'mug'; p.ability = 100; addStone(q, 'ice'); addStone(q, 'fire'); useAbility(r, p); expect(p.stones).toEqual(['fire']); expect(q.stones).toEqual(['ice']); });
  it('Barrier blocks automatically, Receive gains the attacking spell but still takes damage', () => { const r = duel(), [p, q] = r.racers; q.abilityId = 'barrier'; q.ability = 100; hit(r, q, p, 'fire'); expect(q.stun).toBe(0); expect(q.ability).toBe(0); q.abilityId = 'receive'; q.ability = 100; hit(r, q, p, 'fire'); expect(q.stones).toEqual(['fire']); expect(q.stun).toBeGreaterThan(0); });
  it('Magic Plus auto-upgrades the latest stone', () => { const r = solo(), p = r.racers[0]; p.abilityId = 'magic'; p.ability = 100; addStone(p, 'fire'); stepRace(r); expect(p.stones).toEqual(['fire', 'fire']); expect(p.ability).toBe(0); });
});
describe('complete deterministic races', () => {
  for (const id of TRACK_IDS) it(`all six racers finish three laps of ${id} with 36 validated gates`, () => { const r = createRace(id, [makeRacer('p', 'CPU', 0, true)], 3, 831); for (let i = 0; i < 60 * 360 && r.phase !== 'finished'; i++) stepRace(r); expect(r.phase).toBe('finished'); for (const p of r.racers) { expect(p.finishTime, `${p.name}: ${p.s}, gates ${p.gates}`).not.toBeNull(); expect(p.gates).toBe(36); expect(p.lapTimes).toHaveLength(3); expect(p.lapTimes.reduce((a, b) => a + b, 0)).toBeCloseTo(p.finishTime!, 6); expect([p.px, p.pz, p.yaw, p.speed].every(Number.isFinite)).toBe(true); } }, 15000);
  it('identical inputs and seed produce identical positions and results', () => { const a = createRace('forest', [makeRacer('p', 'CPU', 0, true)], 1, 922), b = createRace('forest', [makeRacer('p', 'CPU', 0, true)], 1, 922); tick(a, 120); tick(b, 120); expect(a.racers).toEqual(b.racers); expect(a.events).toEqual(b.events); });
});
